### ISSUE TITLE
Country & Operator Detection

### ISSUE THREAD

**Issue by westruk** [pyshivam/geergit-discussion#23]
Hi.

![photo_2023-04-02_11-29-10](https://user-images.githubusercontent.com/64413688/229336406-b309b969-46b7-4ebd-ab41-e7e497c8cf39.jpg)

I think it's detected because getNetworkCountryIso updated in API 30

https://developer.android.com/reference/android/telephony/TelephonyManager#getNetworkCountryIso(int)

**Comment by pyshivam** [comment]
Okay

**Comment by pyshivam** [comment]
The country is hooked, however for the operator I don't know which method VDInfo using if know that then I may be able to hook it

**Comment by westruk** [comment]
> done

When release?)

**Comment by westruk** [comment]
> The country is hooked, however for the operator I don't know which method VDInfo is using if I know that then I may be able to hook it

Maybe it generated from MCC+MNC string?

https://developer.android.com/reference/android/telephony/SubscriptionInfo#getMccString()

https://developer.android.com/reference/android/telephony/SubscriptionInfo#getMncString()

**Comment by pyshivam** [comment]
thank you so much for finding the problem, both methods are hooked now.

**Comment by westruk** [comment]
> thank you so much for finding the problem, both methods are hooked now.

hmm...don't work on last release

![photo_2023-04-12_11-05-45](https://user-images.githubusercontent.com/64413688/231365577-a0685bc8-3578-468e-94b1-af1057ddfe58.jpg)

**Comment by westruk** [comment]
any news?

**Comment by pyshivam** [comment]
work in progress, currently working on Group feature
